apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4001
      targetPort: 4001
