{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickslot-alb
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app.kubernetes.io/name: quickslot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.loadBalancerName | quote }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | quote }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    {{- if .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/subnets: {{ join "," .Values.ingress.subnets | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: quickslot-kgateway
                port:
                  number: 80
          {{- end }}
{{- end }}
