{{- if .Values.runtimeSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runtimeSecret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app.kubernetes.io/name: quickslot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.runtimeSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
