apiVersion: v1
kind: Service
metadata:
  name: quickslot-kgateway
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app: quickslot-kgateway
spec:
  type: ClusterIP
  selector:
    app: quickslot-kgateway
  ports:
    - port: 80
      targetPort: 8080
