apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app: scheduler-service
spec:
  type: ClusterIP
  selector:
    app: scheduler-service
  ports:
    - port: 4005
      targetPort: 4005
