apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - port: 4003
      targetPort: 4003
