apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    Application: smart-parking
    app: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        Application: smart-parking
        app: frontend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: frontend
          image: {{ .Values.images.frontend }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
